version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    volumes:
      - ./user-service:/usr/src/app
      - ./communicator:/usr/src/app/communicator

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    volumes:
      - ./product-service:/usr/src/app
      - ./communicator:/usr/src/app/communicator

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    depends_on:
      - user-service
      - product-service
    volumes:
      - ./order-service:/usr/src/app
      - ./communicator:/usr/src/app/communicator
